### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): YellowBox.js:80 Error: Failed to embed PDF!

### ISSUE THREAD

**Issue by VanessaChu** [Hopding/react-native-pdf-lib#26]
This is the error

YellowBox.js:80
Error: Failed to embed PDF!
Error: Failed to embed PDF!
    at createErrorFromErrorData (/Users/vanessa/Desktop/vericare_rn/.vscode/.react/index.ios.bundle:10586:17)
    at /Users/vanessa/Desktop/vericare_rn/.vscode/.react/index.ios.bundle:10538:27
    at MessageQueue.__invokeCallback (/Users/vanessa/Desktop/vericare_rn/.vscode/.react/index.ios.bundle:10980:18)
    at /Users/vanessa/Desktop/vericare_rn/.vscode/.react/index.ios.bundle:10725:18
    at MessageQueue.__guardSafe (/Users/vanessa/Desktop/vericare_rn/.vscode/.react/index.ios.bundle:10893:11)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (/Users/vanessa/Desktop/vericare_rn/.vscode/.react/index.ios.bundle:10724:14)
    at /Users/vanessa/Desktop/vericare_rn/.vscode/.react/debuggerWorker.js:124:58
    at process.<anonymous> (/Users/vanessa/Desktop/vericare_rn/.vscode/.react/debuggerWorker.js:35:9)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)

My code:
```
  async capturePdf () {
    const { uriMonthly, uriWeekly } = this.state

    // Create a PDF page with text and images
    const page1 = PDFPage
      .create()
      .setMediaBox(250, 250)
      .drawText('You can add JPG images too!')
      .drawImage(uriWeekly, 'png', {
        x: 5,
        y: 125,
        width: 200,
        height: 100
      })
      .drawImage(uriMonthly, 'png', {
        x: 5,
        y: 25,
        width: 200,
        height: 100
      })

    // Create a new PDF in your app's private Documents directory
    const docsDir = await PDFLib.getDocumentsDirectory()
    const pdfPath = `${docsDir}/sample.pdf`
    console.log(pdfPath)
    PDFDocument
      .create(pdfPath)
      .addPages(page1)
      .write() // Returns a promise that resolves with the PDF's path
      .then(path => {
        console.log('PDF created at: ' + path)
        // Do stuff with your shiny new PDF!
      })
  }
```

I have checked that pdfPath is a valid path

**Comment by Hopding** [comment]
Can you share the paths that are contained in the `uriMonthly` and `uriWeekly` variables? Also, are you sure they are PNG images, not JPG images? And, if you are able to share them, it would be useful to have access to the images themselves so that I can try to reproduce the issue.
